### ISSUE TITLE
Remove gh-pages branch from repository

### ISSUE THREAD

**Issue by fnkr** [destan/github-label-manager#5]
I suggest removing the `gh-pages` branch. The source branch for GitHub pages can be changed in the repository settings.

**Comment by destan** [comment]
why? what's wrong with that name?

**Comment by fnkr** [comment]
When I opened PR #4 I wondered whether I should target `master` or `gh-pages`. Both branches reference the same commit. From my point of view it doesn't make sense to update two branches (unless you wan't to keep a second branch for staging or something?).

**Comment by destan** [comment]
well for such a tiny project you are right, only master will do it, thanks
